apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lets-encrypt-cert
spec:
  dnsNames:
    - ashton.tk
  secretName: lets-encrypt-cert-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer