apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: react-nginx-ingress
spec:
  rules:
  - host: ashton.tk
    http:
      paths:
      - path: "/"
        backend:
          serviceName: react-nginx-service
          servicePort: 80
      - path: "/rita"
        backend:
          serviceName: node-app-service
          servicePort: 80
  - host: rita.ashton.tk
    http:
      paths:
      - path: "/"
        backend:
          serviceName: node-app-service
          servicePort: 80
