apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-fullstack-app
  namespace: pet-project
spec:
  selector:
    matchLabels:
      app: sample-fullstack-app
  template:
    metadata:
      labels:
        app: sample-fullstack-app
    spec:
      containers:
        - name: sample-fullstack-app
          image: logicalogbonna/node-sample-application:main
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: sample-fullstack-config-map
                  key: mongo_uri
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5551
image:
  tag: e292e81d4a6392d872f09f73db5c7beef4791602
---
apiVersion: v1
kind: Service
metadata:
  name: sample-fullstack-app-service
spec:
  selector:
    app: sample-fullstack-app
  ports:
    - port: 80
      targetPort: 5551
image:
  tag: e292e81d4a6392d872f09f73db5c7beef4791602
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sample-fullstack-app-hpa
  namespace: pet-project
  labels:
    app: hpa-auto-scaler
    name: sample-fullstack-app-auto-scaler
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-fullstack-app
  targetCPUUtilizationPercentage: 60
image:
  tag: e292e81d4a6392d872f09f73db5c7beef4791602
