apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-fullstack-app
  namespace: pet-project
spec:
  selector:
    matchLabels:
      app: sample-fullstack-app
  template:
    metadata:
      labels:
        app: sample-fullstack-app
    spec:
      containers:
        - name: sample-fullstack-app
          image: logicalogbonna/node-sample-application:cc29b1c937d46f0ac99ea6a0f6da43becc288f8c
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: sample-fullstack-config-map
                  key: mongo_uri
          resources:
            limits:
              memory: "100Mi"
              cpu: "200m"
          ports:
            - containerPort: 5551
